"""add_insight_tables

Revision ID: d0e41c422fa6
Revises: 20260322_000004
Create Date: 2026-03-22 17:27:04.026094
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0e41c422fa6'
down_revision: Union[str, Sequence[str], None] = '20260322_000004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Text(), nullable=True),
    sa.Column('chunk_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('insight_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_citations_project_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('idx_audit_events_project_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('report_sections')
    op.alter_column('chunks', 'embedding_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chunks_chroma_id'), table_name='chunks', postgresql_where='(chroma_id IS NOT NULL)')
    op.drop_index(op.f('idx_chunks_document_id'), table_name='chunks')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('idx_documents_source_id'), table_name='documents')
    op.drop_constraint(op.f('documents_source_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'sources', ['source_id'], ['id'])
    op.add_column('insights', sa.Column('query', sa.Text(), nullable=False))
    op.add_column('insights', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('insights', sa.Column('findings', sa.JSON(), nullable=True))
    op.add_column('insights', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('insights', sa.Column('model_id', sa.String(length=128), nullable=True))
    op.add_column('insights', sa.Column('run_id', sa.Uuid(), nullable=True))
    op.add_column('insights', sa.Column('status', sa.String(length=20), nullable=False))
    op.drop_index(op.f('idx_insights_project_id'), table_name='insights')
    op.drop_constraint(op.f('insights_project_id_fkey'), 'insights', type_='foreignkey')
    op.drop_constraint(op.f('insights_processing_run_id_fkey'), 'insights', type_='foreignkey')
    op.create_foreign_key(None, 'insights', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'insights', 'processing_runs', ['run_id'], ['id'])
    op.drop_column('insights', 'title')
    op.drop_column('insights', 'updated_at')
    op.drop_column('insights', 'processing_run_id')
    op.drop_column('insights', 'content')
    op.drop_column('insights', 'confidence_score')
    op.alter_column('jobs', 'job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('jobs', 'progress',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_jobs_idempotency_key'), table_name='jobs', postgresql_where='(idempotency_key IS NOT NULL)')
    op.drop_index(op.f('idx_jobs_project_status'), table_name='jobs')
    op.drop_constraint(op.f('jobs_project_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_source_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'projects', ['project_id'], ['id'])
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'queue_name')
    op.drop_column('jobs', 'idempotency_key')
    op.drop_column('jobs', 'error_code')
    op.drop_column('jobs', 'finished_at')
    op.drop_column('jobs', 'attempt_count')
    op.alter_column('processing_runs', 'run_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('processing_runs', 'retrieval_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('processing_runs', 'run_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_processing_runs_project_id'), table_name='processing_runs')
    op.drop_constraint(op.f('processing_runs_project_id_fkey'), 'processing_runs', type_='foreignkey')
    op.drop_constraint(op.f('processing_runs_parent_run_id_fkey'), 'processing_runs', type_='foreignkey')
    op.drop_constraint(op.f('processing_runs_job_id_fkey'), 'processing_runs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_runs', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'processing_runs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'processing_runs', 'processing_runs', ['parent_run_id'], ['id'])
    op.alter_column('projects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('projects', 'updated_at')
    op.alter_column('provider_credentials', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('provider_credentials', 'chat_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('provider_credentials', 'embedding_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.drop_index(op.f('idx_provider_credentials_project_id'), table_name='provider_credentials')
    op.drop_index(op.f('uq_provider_credentials_project'), table_name='provider_credentials')
    op.create_unique_constraint('uq_provider_credentials_project', 'provider_credentials', ['project_id', 'provider'])
    op.drop_constraint(op.f('provider_credentials_project_id_fkey'), 'provider_credentials', type_='foreignkey')
    op.create_foreign_key(None, 'provider_credentials', 'projects', ['project_id'], ['id'])
    op.alter_column('query_runs', 'filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_query_runs_project_id'), table_name='query_runs')
    op.drop_constraint(op.f('query_runs_project_id_fkey'), 'query_runs', type_='foreignkey')
    op.create_foreign_key(None, 'query_runs', 'projects', ['project_id'], ['id'])
    op.add_column('reports', sa.Column('run_id', sa.Uuid(), nullable=True))
    op.alter_column('reports', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reports', 'format',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('reports', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.drop_index(op.f('idx_reports_project_id'), table_name='reports')
    op.drop_constraint(op.f('reports_processing_run_id_fkey'), 'reports', type_='foreignkey')
    op.drop_constraint(op.f('reports_project_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'processing_runs', ['run_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'])
    op.drop_column('reports', 'processing_run_id')
    op.drop_column('reports', 'storage_path')
    op.drop_column('reports', 'updated_at')
    op.alter_column('sources', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sources', 'checksum',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('sources', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.drop_index(op.f('idx_sources_project_id'), table_name='sources')
    op.drop_constraint(op.f('sources_project_id_fkey'), 'sources', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.create_foreign_key(op.f('sources_project_id_fkey'), 'sources', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_sources_project_id'), 'sources', ['project_id'], unique=False)
    op.alter_column('sources', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('sources', 'checksum',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sources', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('reports', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('processing_run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_project_id_fkey'), 'reports', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reports_processing_run_id_fkey'), 'reports', 'processing_runs', ['processing_run_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.alter_column('reports', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::text"))
    op.alter_column('reports', 'format',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reports', 'report_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reports', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('reports', 'run_id')
    op.drop_constraint(None, 'query_runs', type_='foreignkey')
    op.create_foreign_key(op.f('query_runs_project_id_fkey'), 'query_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_query_runs_project_id'), 'query_runs', ['project_id'], unique=False)
    op.alter_column('query_runs', 'filters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'provider_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('provider_credentials_project_id_fkey'), 'provider_credentials', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_provider_credentials_project', 'provider_credentials', type_='unique')
    op.create_index(op.f('uq_provider_credentials_project'), 'provider_credentials', ['project_id', 'provider'], unique=True)
    op.create_index(op.f('idx_provider_credentials_project_id'), 'provider_credentials', ['project_id'], unique=False)
    op.alter_column('provider_credentials', 'embedding_model',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('provider_credentials', 'chat_model',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('provider_credentials', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'processing_runs', type_='foreignkey')
    op.drop_constraint(None, 'processing_runs', type_='foreignkey')
    op.drop_constraint(None, 'processing_runs', type_='foreignkey')
    op.create_foreign_key(op.f('processing_runs_job_id_fkey'), 'processing_runs', 'jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('processing_runs_parent_run_id_fkey'), 'processing_runs', 'processing_runs', ['parent_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('processing_runs_project_id_fkey'), 'processing_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_processing_runs_project_id'), 'processing_runs', ['project_id'], unique=False)
    op.alter_column('processing_runs', 'run_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('processing_runs', 'retrieval_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('processing_runs', 'run_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('jobs', sa.Column('attempt_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('idempotency_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('queue_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_source_id_fkey'), 'jobs', 'sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('jobs_project_id_fkey'), 'jobs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_jobs_project_status'), 'jobs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.alter_column('jobs', 'progress',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('jobs', 'job_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('insights', sa.Column('confidence_score', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('insights', sa.Column('processing_run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('insights', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('insights', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.create_foreign_key(op.f('insights_processing_run_id_fkey'), 'insights', 'processing_runs', ['processing_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('insights_project_id_fkey'), 'insights', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_insights_project_id'), 'insights', ['project_id'], unique=False)
    op.drop_column('insights', 'status')
    op.drop_column('insights', 'run_id')
    op.drop_column('insights', 'model_id')
    op.drop_column('insights', 'provider')
    op.drop_column('insights', 'findings')
    op.drop_column('insights', 'summary')
    op.drop_column('insights', 'query')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_source_id_fkey'), 'documents', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('idx_chunks_chroma_id'), 'chunks', ['chroma_id'], unique=True, postgresql_where='(chroma_id IS NOT NULL)')
    op.alter_column('chunks', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('chunks', 'embedding_model',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('report_sections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_sections_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('report_sections_pkey'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('audit_events_project_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    op.create_index(op.f('idx_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('insight_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('claim_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_span', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('citations_chunk_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('citations_document_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], name=op.f('citations_insight_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('citations_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_run_id'], ['query_runs.id'], name=op.f('citations_query_run_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('citations_report_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('citations_source_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('citations_pkey'))
    )
    op.create_index(op.f('idx_citations_project_id'), 'citations', ['project_id'], unique=False)
    op.drop_table('report_insights')
    op.drop_table('insight_citations')
    # ### end Alembic commands ###
