export const appRoutes = [
    { href: "/projects", label: "Projects" },
    { href: "/sources", label: "Sources" },
    { href: "/jobs", label: "Jobs" },
    { href: "/actions", label: "Actions" },
    { href: "/query", label: "Query" },
    { href: "/settings", label: "Settings" },
    { href: "/insights", label: "Insights" },
    { href: "/reports", label: "Reports" },
    { href: "/flashcards", label: "Flashcards" },
    { href: "/quiz", label: "Quiz" },
    { href: "/study-guide", label: "Study Guide" },
    { href: "/mind-map", label: "Mind Map" },
    { href: "/mesh", label: "Mesh Graph" },
] as const;
