services:
  postgres:
    image: postgres:16
    container_name: cogniflow-postgres
    environment:
      POSTGRES_DB: cogniflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cogniflow-postgres-data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma:1.0.20
    container_name: cogniflow-chroma
    ports:
      - "8001:8000"
    volumes:
      - cogniflow-chroma-data:/data
    restart: unless-stopped

volumes:
  cogniflow-postgres-data:
  cogniflow-chroma-data:
