# Fill this IP from Terraform output:
#   terraform -chdir=infra/terraform output app_server_public_ip

[app_servers]
app01 ansible_host=47.131.213.6 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/sing.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
